/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import "@workspace/ui/globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Project CRM Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`antialiased`}>
        <Toaster richColors position="top-right" />
        {children}
      </body>
    </html>
  );
}
